# TENSORS

In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [2]:
#creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20])>

In [4]:
vector.ndim

1

In [5]:
scalar.ndim

0

In [6]:
matrix = tf.constant([[10,20,30],
                     [30,40,50]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10., 20., 30.],
       [30., 40., 50.]], dtype=float16)>

In [7]:
matrix.ndim

2

## Definitions
* scalar: singular number 
* vector: a number with a direction  1 dimentional
* matrix: a 2 dimentional array 
* tensor: n dimentional array of numbers

## creating tensors with tf.Variable()

In [8]:
changeable = tf.Variable([10,20,30])
changeable[0].assign(200)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([200,  20,  30])>

* using tf.Variable we can change the initially assigned values to the sensor

# note that we cannot assign using the assignment operator in python
* ##### we should instead use the **assign** method provided by the tensor

In [9]:
unchangeable = tf.constant([10,20])
#unchangeable[0].assign(200)

throws an error while using assign method

# Random tensor

In [10]:
tf.random.set_seed(5)
ran_1 = tf.random.normal( [2,2] ,seed=42)
tf.random.set_seed(5)
ran_2 = tf.random.normal([2,2] , seed=42)
ran_1,ran_2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.1051298 , 1.6772811 ],
        [0.49890184, 0.54185474]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.1051298 , 1.6772811 ],
        [0.49890184, 0.54185474]], dtype=float32)>)

# Shuffling tensors

In [11]:
unshuffled = tf.constant([[10,20],[30,40]])
tf.random.shuffle(unshuffled)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

### Creating tensors from numpy array

In [12]:
import numpy as np
np_A = np.arange(1,25).reshape(-1,3)
np_A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [13]:
A = tf.constant(np_A, shape=(2,4,3))
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [14]:
np_A.ndim

2

In [15]:
A.ndim

3

In [16]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [17]:
tf.ones([2,2] , dtype=tf.int16)

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1]], dtype=int16)>

In [50]:
tf.range(1,11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

to convert tensor into a  numpy array use `np.array(tensor_name)`

In [63]:
a = tf.constant(np.array([1,3,5]))
print(type(a))
print(f"a = {a}")
a = a.numpy()
print(type(a))
print(f"a = {a}")

<class 'tensorflow.python.framework.ops.EagerTensor'>
a = [1 3 5]
<class 'numpy.ndarray'>
a = [1 3 5]


# INFORMATION FROM TENSOR
* `shape` - return shape of the tensor
* `size` - returns the number of elements
* `ndim` - returns the number of dimentions of the tensor

In [18]:
test = tf.zeros(shape=(2,3,4))

In [19]:
print(f"data type of the tensor {test.dtype}")
print(f"number of dimentions of the tensor {test.ndim}")
print(f"shape of the tensor {test.shape}")
print(f"number of elements in the tensor {tf.size(test).numpy()}")

data type of the tensor <dtype: 'float32'>
number of dimentions of the tensor 3
shape of the tensor (2, 3, 4)
number of elements in the tensor 24


# MANIPULATING TENSORS

In [20]:
tensor = tf.constant([[20,30],[40,50]])

In [21]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [50, 60]])>

In [22]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 300],
       [400, 500]])>

> mostly use the tf funciton since the run in gpu therefore faster

In [23]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 300],
       [400, 500]])>

In [24]:
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

# MATRIX MULTIPLICATION

> matrix multiplication is also known as dot product

they can be calculated in two ways
* using `tf.linalg.matmul()` function
* using `tf.tensordot()` function
* using `@` operator

In [25]:
A = tf.constant( [[1,2,5],[7,2,1],[3,3,3]])
B = tf.constant([[3,5],[6,7],[1,8]])
A,B

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [26]:
tf.linalg.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [27]:
A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

### reshaping tensors

In [28]:
a = tf.zeros((4))
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [29]:
a = tf.reshape(a,shape=(2,2))

In [30]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

#### transpose

In [31]:
a = tf.constant([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
tf.transpose(a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])>

In [32]:
print(A,B)
tf.tensordot(A,B,axes=1)

tf.Tensor(
[[1 2 5]
 [7 2 1]
 [3 3 3]], shape=(3, 3), dtype=int32) tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

## CHANGING THE DATATYPE OF THE TENSOR

we can change the datatype of the tensor using the `tf.cast` function

In [33]:
tensor = tf.zeros((2,2))
tensor.dtype

tf.float32

In [34]:
new_tensor = tf.cast(tensor , dtype = tf.float16)
new_tensor.dtype

tf.float16

### AGGEREGATING TENSORS

they are you reduce or filter out some data
* `tf.abs()` return the absolute value of the tensor
* `tf.reduve_max() or tf.reduce_min()` returns min or max value respectively
* `tf.math.reduce_std() or tf.math.reduce_variance` returns the std dev or var repectively

In [35]:
d = tf.constant([10,-20,30])

In [36]:
tf.abs(d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [37]:
tf.reduce_max(d)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [38]:
tf.reduce_min(d)

<tf.Tensor: shape=(), dtype=int32, numpy=-20>

In [39]:
rand = tf.constant(np.random.randint(0,100,20))
rand = tf.cast(rand,dtype = tf.float16)

In [40]:
tf.math.reduce_std(rand)

<tf.Tensor: shape=(), dtype=float16, numpy=30.33>

In [41]:
tf.math.reduce_variance(rand)

<tf.Tensor: shape=(), dtype=float16, numpy=920.0>

### POSITIONAL MIN AND MAX

`tf.argmin() or tf.argmax()`method is used to return the index of the min value or max value respectively

In [42]:
tf.random.set_seed(42)
tensor = tf.random.normal((50,))
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
       -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 , -0.56668764,
       -0.35819843,  0.88698626,  0.5274477 ,  0.70402247, -0.33421248],
      dtype=float32)>

In [45]:
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=-3.0258412>

In [47]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=8>